# Generated by Django 4.2.8 on 2023-12-13 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_opponent_id_alter_chatroom_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='opponent_id',
        ),
    ]
