# Generated by Django 4.2.8 on 2023-12-07 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_globalchatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('participants', models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserProfileModel',
            new_name='UserProfile',
        ),
        migrations.RemoveField(
            model_name='chatnotification',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='chatnotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='globalchatmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatModel',
        ),
        migrations.DeleteModel(
            name='ChatNotification',
        ),
        migrations.DeleteModel(
            name='GlobalChatMessage',
        ),
    ]
