# Generated by Django 4.2.8 on 2023-12-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_message_rename_userprofilemodel_userprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='participants',
            new_name='member',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='roomId',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
