# Generated by Django 4.2.8 on 2023-12-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_participants_chatroom_member_chatroom_roomid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='name',
        ),
    ]
